package com.yspay.sample.dubboprovider.repository;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.yspay.sample.dubboprovider.entity.Order;

public interface OrderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ORDER
	 * @mbg.generated  Wed May 09 16:17:07 CST 2018
	 */
	@Delete({ "delete from T_ORDER",
			"where ORDER_SEQ_ID = #{orderSeqId,jdbcType=VARCHAR}" })
	int deleteByPrimaryKey(String orderSeqId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ORDER
	 * @mbg.generated  Wed May 09 16:17:07 CST 2018
	 */
	@Insert({ "insert into T_ORDER (ORDER_SEQ_ID, ORDER_ID, ",
			"USER_ID, STATUS, ", "CREATE_DATE)",
			"values (#{orderSeqId,jdbcType=VARCHAR}, #{orderId,jdbcType=VARCHAR}, ",
			"#{userId,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, ",
			"#{createDate,jdbcType=TIMESTAMP})" })
	int insert(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ORDER
	 * @mbg.generated  Wed May 09 16:17:07 CST 2018
	 */
	@InsertProvider(type = OrderSqlProvider.class, method = "insertSelective")
	int insertSelective(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ORDER
	 * @mbg.generated  Wed May 09 16:17:07 CST 2018
	 */
	@Select({ "select", "ORDER_SEQ_ID, ORDER_ID, USER_ID, STATUS, CREATE_DATE",
			"from T_ORDER",
			"where ORDER_SEQ_ID = #{orderSeqId,jdbcType=VARCHAR}" })
	@Results({
			@Result(column = "ORDER_SEQ_ID", property = "orderSeqId", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "ORDER_ID", property = "orderId", jdbcType = JdbcType.VARCHAR),
			@Result(column = "USER_ID", property = "userId", jdbcType = JdbcType.VARCHAR),
			@Result(column = "STATUS", property = "status", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CREATE_DATE", property = "createDate", jdbcType = JdbcType.TIMESTAMP) })
	Order selectByPrimaryKey(String orderSeqId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ORDER
	 * @mbg.generated  Wed May 09 16:17:07 CST 2018
	 */
	@UpdateProvider(type = OrderSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ORDER
	 * @mbg.generated  Wed May 09 16:17:07 CST 2018
	 */
	@Update({ "update T_ORDER", "set ORDER_ID = #{orderId,jdbcType=VARCHAR},",
			"USER_ID = #{userId,jdbcType=VARCHAR},",
			"STATUS = #{status,jdbcType=VARCHAR},",
			"CREATE_DATE = #{createDate,jdbcType=TIMESTAMP}",
			"where ORDER_SEQ_ID = #{orderSeqId,jdbcType=VARCHAR}" })
	int updateByPrimaryKey(Order record);
}