package com.yspay.sample.dubboprovider.repository;

import org.apache.ibatis.jdbc.SQL;

import com.yspay.sample.dubboprovider.entity.OrderItem;

public class OrderItemSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ORDER_ITEM
	 * @mbg.generated  Wed May 09 16:17:07 CST 2018
	 */
	public String insertSelective(OrderItem record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("T_ORDER_ITEM");
		if (record.getItemId() != null) {
			sql.VALUES("ITEM_ID", "#{itemId,jdbcType=VARCHAR}");
		}
		if (record.getOrderSeqId() != null) {
			sql.VALUES("ORDER_SEQ_ID", "#{orderSeqId,jdbcType=VARCHAR}");
		}
		if (record.getOrderId() != null) {
			sql.VALUES("ORDER_ID", "#{orderId,jdbcType=VARCHAR}");
		}
		if (record.getUserId() != null) {
			sql.VALUES("USER_ID", "#{userId,jdbcType=VARCHAR}");
		}
		if (record.getCreateDate() != null) {
			sql.VALUES("CREATE_DATE", "#{createDate,jdbcType=TIMESTAMP}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ORDER_ITEM
	 * @mbg.generated  Wed May 09 16:17:07 CST 2018
	 */
	public String updateByPrimaryKeySelective(OrderItem record) {
		SQL sql = new SQL();
		sql.UPDATE("T_ORDER_ITEM");
		if (record.getOrderSeqId() != null) {
			sql.SET("ORDER_SEQ_ID = #{orderSeqId,jdbcType=VARCHAR}");
		}
		if (record.getOrderId() != null) {
			sql.SET("ORDER_ID = #{orderId,jdbcType=VARCHAR}");
		}
		if (record.getUserId() != null) {
			sql.SET("USER_ID = #{userId,jdbcType=VARCHAR}");
		}
		if (record.getCreateDate() != null) {
			sql.SET("CREATE_DATE = #{createDate,jdbcType=TIMESTAMP}");
		}
		sql.WHERE("ITEM_ID = #{itemId,jdbcType=VARCHAR}");
		return sql.toString();
	}
}