package com.yspay.sample.dubboprovider.repository;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import com.yspay.sample.dubboprovider.entity.OrderItem;

public interface OrderItemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ORDER_ITEM
	 * @mbg.generated  Wed May 09 16:17:07 CST 2018
	 */
	@Delete({ "delete from T_ORDER_ITEM",
			"where ITEM_ID = #{itemId,jdbcType=VARCHAR}" })
	int deleteByPrimaryKey(String itemId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ORDER_ITEM
	 * @mbg.generated  Wed May 09 16:17:07 CST 2018
	 */
	@Insert({ "insert into T_ORDER_ITEM (ITEM_ID, ORDER_SEQ_ID, ",
			"ORDER_ID, USER_ID, ", "CREATE_DATE)",
			"values (#{itemId,jdbcType=VARCHAR}, #{orderSeqId,jdbcType=VARCHAR}, ",
			"#{orderId,jdbcType=VARCHAR}, #{userId,jdbcType=VARCHAR}, ",
			"#{createDate,jdbcType=TIMESTAMP})" })
	int insert(OrderItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ORDER_ITEM
	 * @mbg.generated  Wed May 09 16:17:07 CST 2018
	 */
	@InsertProvider(type = OrderItemSqlProvider.class, method = "insertSelective")
	int insertSelective(OrderItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ORDER_ITEM
	 * @mbg.generated  Wed May 09 16:17:07 CST 2018
	 */
	@Select({ "select", "ITEM_ID, ORDER_SEQ_ID, ORDER_ID, USER_ID, CREATE_DATE",
			"from T_ORDER_ITEM", "where ITEM_ID = #{itemId,jdbcType=VARCHAR}" })
	@Results({
			@Result(column = "ITEM_ID", property = "itemId", jdbcType = JdbcType.VARCHAR, id = true),
			@Result(column = "ORDER_SEQ_ID", property = "orderSeqId", jdbcType = JdbcType.VARCHAR),
			@Result(column = "ORDER_ID", property = "orderId", jdbcType = JdbcType.VARCHAR),
			@Result(column = "USER_ID", property = "userId", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CREATE_DATE", property = "createDate", jdbcType = JdbcType.TIMESTAMP) })
	OrderItem selectByPrimaryKey(String itemId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ORDER_ITEM
	 * @mbg.generated  Wed May 09 16:17:07 CST 2018
	 */
	@UpdateProvider(type = OrderItemSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(OrderItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table T_ORDER_ITEM
	 * @mbg.generated  Wed May 09 16:17:07 CST 2018
	 */
	@Update({ "update T_ORDER_ITEM",
			"set ORDER_SEQ_ID = #{orderSeqId,jdbcType=VARCHAR},",
			"ORDER_ID = #{orderId,jdbcType=VARCHAR},",
			"USER_ID = #{userId,jdbcType=VARCHAR},",
			"CREATE_DATE = #{createDate,jdbcType=TIMESTAMP}",
			"where ITEM_ID = #{itemId,jdbcType=VARCHAR}" })
	int updateByPrimaryKey(OrderItem record);
}